"""
checklist.py — Collaborative Packing Hub models.

Two tables:
  checklist_items   — individual packing items for a trip, with assignment + packed status.
  checklist_snapshots — optional metadata (not used directly; the hub is built off items).

Design decisions:
- One pool of items per trip (no separate "checklists" table needed; the trip_id IS the
  checklist identity). This keeps the data model flat and the API simple.
- assigned_to_participant_id is nullable — an item is "shared / unassigned" when NULL.
- is_packed is a boolean updated in-place; real-time sync happens over WebSocket broadcast
  (existing ws.py manager) after any PATCH.
- suggested_by tracks whether an item was generated by the Smart Suggestion engine
  ("system") or added manually ("participant:<id>").
- category groups items for the UI: "travel_docs", "clothing", "toiletries",
  "electronics", "shared_gear", "food_drink", "first_aid", "misc".
"""

from __future__ import annotations

import uuid

from sqlalchemy import Boolean, Column, DateTime, ForeignKey, Index, Integer, String, Uuid
from sqlalchemy.sql import func

from app.db.database import Base


class ChecklistItem(Base):
    __tablename__ = "checklist_items"
    __table_args__ = (
        Index("ix_checklist_items_trip_id", "trip_id"),
        Index("ix_checklist_items_trip_packed", "trip_id", "is_packed"),
    )

    id = Column(Uuid, primary_key=True, default=uuid.uuid4)

    # Parent trip
    trip_id = Column(
        Uuid, ForeignKey("trips.id", ondelete="CASCADE"), nullable=False
    )

    # Item content
    name = Column(String(200), nullable=False)
    category = Column(String(50), nullable=False, default="misc")
    # Who suggested this: "system" (Smart Suggestion engine) or "participant:<uuid>"
    suggested_by = Column(String(100), nullable=False, default="system")
    notes = Column(String(500), nullable=True)

    # Divvy Up: nullable → shared / unassigned
    assigned_to_participant_id = Column(
        Uuid, ForeignKey("participants.id", ondelete="SET NULL"), nullable=True
    )

    # Real-time sync flag
    is_packed = Column(Boolean, nullable=False, default=False)
    packed_at = Column(DateTime(timezone=True), nullable=True)
    packed_by_participant_id = Column(
        Uuid, ForeignKey("participants.id", ondelete="SET NULL"), nullable=True
    )

    # Ordering within a category
    sort_order = Column(Integer, nullable=False, default=0)

    created_at = Column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
