"""add_destinations_table

Revision ID: 27009f1e60d2
Revises: b0291ac57763
Create Date: 2026-06-05 14:21:13.724368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27009f1e60d2'
down_revision: Union[str, None] = 'b0291ac57763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destinations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('budget_midpoint', sa.Integer(), nullable=False),
    sa.Column('budget_flexibility', sa.Float(), nullable=False),
    sa.Column('vibes', sa.JSON(), nullable=False),
    sa.Column('climate', sa.String(length=20), nullable=False),
    sa.Column('activity_level', sa.String(length=20), nullable=False),
    sa.Column('feature_vector', sa.JSON(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('destinations')
    # ### end Alembic commands ###
