"""initial_schema

Revision ID: b0291ac57763
Revises: 
Create Date: 2026-05-29 21:47:10.274173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0291ac57763'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ml_run_results', sa.Column('cluster_count', sa.JSON(), nullable=True))
    op.add_column('ml_run_results', sa.Column('silhouette_score', sa.Float(), nullable=True))
    op.add_column('recommendations', sa.Column('quality_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendations', 'quality_score')
    op.drop_column('ml_run_results', 'silhouette_score')
    op.drop_column('ml_run_results', 'cluster_count')
    # ### end Alembic commands ###
