"""add_db_indexes

Revision ID: cd28fbd46a9f
Revises: 054686e44a48
Create Date: 2026-06-10 14:39:53.331265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd28fbd46a9f'
down_revision: Union[str, None] = '054686e44a48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_participants_survey_token', 'participants', ['survey_token'], unique=False)
    op.create_index('ix_participants_trip_id', 'participants', ['trip_id'], unique=False)
    op.create_index('ix_recommendations_trip_id', 'recommendations', ['trip_id'], unique=False)
    op.create_index('ix_recommendations_trip_rank', 'recommendations', ['trip_id', 'rank'], unique=False)
    op.create_index('ix_survey_responses_participant_id', 'survey_responses', ['participant_id'], unique=False)
    op.create_index('ix_survey_responses_trip_id', 'survey_responses', ['trip_id'], unique=False)
    op.create_index('ix_votes_trip_id', 'votes', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_votes_trip_id', table_name='votes')
    op.drop_index('ix_survey_responses_trip_id', table_name='survey_responses')
    op.drop_index('ix_survey_responses_participant_id', table_name='survey_responses')
    op.drop_index('ix_recommendations_trip_rank', table_name='recommendations')
    op.drop_index('ix_recommendations_trip_id', table_name='recommendations')
    op.drop_index('ix_participants_trip_id', table_name='participants')
    op.drop_index('ix_participants_survey_token', table_name='participants')
    # ### end Alembic commands ###
